/**
 * ObIdl_MAccPrtInvIAccPrtInv.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.asiainfo.obd.AccPrtInv;

import com.asiainfo.obd.AccPrtInv.holders.*;

public interface ObIdl_MAccPrtInv_IAccPrtInv extends java.rmi.Remote {
    public int query_invoice(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccPrtInvDefSInvContentIn sIn, ObIdl_MAccPrtInvDefSInvContentListHolder listInvContent, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int query_invoiceDtl(MObdCommonSOBSessionProperty[] sSession, long llSoNbr, long llSeqNbr, int iRegionCode, java.lang.String strMonth, ObIdl_MAccPrtInvDefSInvcDtlListHolder listInvcDtl, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int print_invoice(MObdCommonSOBSessionProperty[] sSession, short nFlag, short nPrintCount, long llSoNbr, long llSeqNbr, int iOpId, java.lang.String strReason, int iRegionCode, java.lang.String strMonth, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int print_max(MObdCommonSOBSessionProperty[] sSession, int iRegionCode, javax.xml.rpc.holders.IntHolder iPrtMaxCnt, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int query_regInvoice(MObdCommonSOBSessionProperty[] sSession, short nPrintCount, short nIsAdCon, short nIsCoinCredit, ObIdl_MAccPrtInvDefSBankTrustQryIn sIn, ObIdl_MAccPrtInvDefSInvContentListHolder listInvContent, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int query_invoiceAux(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccPrtInvDefSInvContentIn sIn, ObIdl_MAccPrtInvDefSInvAuxContentListHolder listInvContent, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int query_spInvoice(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccPrtInvDefSSpInvContentIn sIn, ObIdl_MAccPrtInvDefSSpInvContentListHolder listSpInvContent, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int query_cancelInvc(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccPrtInvDefSInvCancelIn[] listIn, ObIdl_MAccPrtInvDefSInvCancelListHolder listInvContent, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int print_invoiceRes(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccPrtInvDefSInvPrintIn sIn, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int modify_invcDtl(MObdCommonSOBSessionProperty[] sSession, long llSoNbr, long llSeqNbr, int iRegionCode, java.lang.String strMonth, java.lang.String strInvcDtl, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int query_receipt(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccPrtInvDefSInvcQryIn sIn, ObIdl_MAccCommonSAccInvcRecInfoListHolder listInvcRecInfo, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int process_taxInfo(MObdCommonSOBSessionProperty[] sSession, java.lang.String strTaxInvcInfo, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int update_printCount(MObdCommonSOBSessionProperty[] sSession, int iRegionCode, java.lang.String strPhoneId, java.lang.String strMonth, long llOpId, long llInvcNumSeq, java.lang.String strRemark, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_minusInvoice(MObdCommonSOBSessionProperty[] sSession, int iRegionCode, java.lang.String strMonth, long llOpId, long llSoNbrOld, long llSoNbr, long llInvcNumSeq, short nInvcSts, java.lang.String strRemark, ObIdl_MAccCommonSAccInvcRecInfoListHolder listInvcRecInfo, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int query_arcInvoice(MObdCommonSOBSessionProperty[] sSession, long llOpId, long llAcctId, java.lang.String strPhoneId, int iRegionCode, java.lang.String strMonthBegin, java.lang.String strMonthEnd, long llInvcNumSeq, java.lang.String strRemark, int iInvcCallFlag, ObIdl_MAccCommonSAccInvcRecInfoListHolder listInvcRecInfo, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int prt_otaReceipt(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccPrtInvDefSPrtOtaReceiptIn sIn, ObIdl_MAccCommonSAccInvcRecInfoHolder sInvcRecInfo, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int qry_prepayInvcInfo(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccPrtInvDefSPrepayInvcQryIn sIn, ObIdl_MAccPrtInvDefSInvcInfoListHolder listInvcInfo, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int upd_receiptInfo(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccPrtInvDefSInvcUpdCond sIn1, ObIdl_MAccPrtInvDefSInvcUpdResult sIn2, javax.xml.rpc.holders.StringHolder strOtherSoNbr, ObIdl_MAccCommonSAccInvcRecInfoListHolder listInvcInfo, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int query_receiptSpdb(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccPrtInvDefSInvcQryInSpdb sIn, ObIdl_MAccCommonSAccInvcRecInfoListHolder listInvcRecInfo, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int update_printCountSpdb(MObdCommonSOBSessionProperty[] sSession, java.lang.String strPhoneId, java.lang.String strMonth, long llOpId, long llInvcNumSeq, java.lang.String strOtherSoNbr, java.lang.String strSpdbQrySeq, java.lang.String strPrintTime, java.lang.String strReserve, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int adjust_taxInvoiceReason(MObdCommonSOBSessionProperty[] sSession, int iOpId, int iSoOrgid, java.lang.String strOtherSoNbr, int iPayType, ObIdl_MBusiChargeDefSAccBusiReceiptType[] listReceipt, ObIdl_MBusiChargeDefSReceiptAdjustReason[] listReceiptReason, ObIdl_MAccPrtInvDefSTaxAccInvcRecInfoListHolder listTaxInvcRecInfoOut, long llRetSoNbr, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int query_taxReceipt(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccPrtInvDefSTaxInvcQryIn sIn, ObIdl_MAccPrtInvDefSTaxAccInvcRecInfoListHolder listTaxInvcRecInfoOut, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int update_taxInvoice(MObdCommonSOBSessionProperty[] sSession, long llOpId, int iSoOrgid, java.lang.String strPhoneId, java.lang.String strMonth, long llInvcNumSeq, java.lang.String strInvoiceNo, java.lang.String strInvoiceNum, java.lang.String strTaxMachineCode, java.lang.String strPrtTime, java.lang.String strRemark, java.lang.String strInvcPrtInfo, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
}
