/**
 * ObIdl_MAccTranBilITraPpy.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.asiainfo.obd.AccTranBil;
import com.asiainfo.obd.AccTranBil.holders.*;

public interface ObIdl_MAccTranBil_ITraPpy extends java.rmi.Remote {
    public int do_exec(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSAccTranBilIn sIn, javax.xml.rpc.holders.LongHolder llRetSoNbr, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_selectPpy(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSAccQryPpyIn sIn, ObIdl_MAccTranBilSAccQryPpyOutListHolder listOut, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_mppyDate(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSAccModiDateIn sIn, javax.xml.rpc.holders.LongHolder llRetSoNbr, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_backout(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSBackOutBook sIn, ObIdl_MAccTranBilSBackOutBookHolder sOut, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_unPpyRefund(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSUnPpyRefundIn sIn, javax.xml.rpc.holders.LongHolder llRetSoNbr, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_execReturnFee(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSAccTranBilIn sIn, javax.xml.rpc.holders.LongHolder llRetSoNbr, ObIdl_MAccTranBilSReturnAccListHolder listAccTraAcct, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_addBatchPay(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSBatchInfo sBatchInfo, ObIdl_MAccTranBilSAccBatchPay[] listInBatchPay, ObIdl_MAccTranBilSAccBatchPayListHolder listOutBatchPay, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_queryBatchPay(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSQueryBatchPayIn sIn, ObIdl_MAccTranBilSAccBatchPayListHolder listOutBatchPay, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_batchUnPay(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSBatchInfo sBatchInfo, ObIdl_MAccTranBilSAccBatchPay[] listInBatchPay, ObIdl_MAccTranBilSAccBatchPayListHolder listOutBatchPay, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int get_channelPayAcctId(MObdCommonSOBSessionProperty[] sSession, int iOpId, int iSoOrgId, java.lang.String strPhoneId, ObIdl_MAccTranBilSAgentRecruitAccListHolder listAgentRecruitAcc, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_agentRecruitAcc(MObdCommonSOBSessionProperty[] sSession, int iOpId, int iSoOrgId, ObIdl_MAccTranBilSRecruitAccCond sRecruitAccCond, ObIdl_MAccTranBilSRecruitAccOutHolder sRecruitAccOut, javax.xml.rpc.holders.LongHolder llRetSoNbr, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_agentRecruitAccTrans(MObdCommonSOBSessionProperty[] sSession, int iOpId, int iSoOrgId, ObIdl_MAccTranBilSRecruitAccTransCond sRecruitAccTransCond, ObIdl_MAccTranBilSRecruitAccTransOutHolder sRecruitAccTransOut, javax.xml.rpc.holders.LongHolder llDoneCode, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int get_agentOrgDept(MObdCommonSOBSessionProperty[] sSession, int iOpId, int iSoOrgId, long llChannelId, int iProvinceId, int iCityId, int iRegionType, int iRegionDetail, java.lang.String strDeptName, int iChannelType, ObIdl_MAccTranBilSAgentOrgDeptListHolder listAgentDept, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_agentBusiFee(MObdCommonSOBSessionProperty[] sSession, int iOpId, int iSoOrgId, ObIdl_MAccTranBilSAgentBusiFeeCond sAgentBusiFeeCond, javax.xml.rpc.holders.LongHolder llRetSoNbr, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int get_agentAirDepositParam(MObdCommonSOBSessionProperty[] sSession, int iOpId, int iSoOrgId, ObIdl_MAccTranBilSAgentAirDepParamCond sAgentAirDepParamCond, ObIdl_MAccTranBilSAgentAirDepositParamListHolder listAgentAirDepositParam, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int add_agentAirDepositParam(MObdCommonSOBSessionProperty[] sSession, int iOpId, int iSoOrgId, ObIdl_MAccTranBilSAgentAirDepositParam sAgentAirDepositParam, javax.xml.rpc.holders.LongHolder llDoneCode, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int chg_agentAirDepositParam(MObdCommonSOBSessionProperty[] sSession, int iOpId, int iSoOrgId, ObIdl_MAccTranBilSAgentAirDepositParam sAgentAirDepositParam, javax.xml.rpc.holders.LongHolder llDoneCode, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int del_agentAirDepositParam(MObdCommonSOBSessionProperty[] sSession, int iOpId, int iSoOrgId, ObIdl_MAccTranBilSAgentAirDepositParam sAgentAirDepositParam, javax.xml.rpc.holders.LongHolder llDoneCode, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int get_agentAccInfo(MObdCommonSOBSessionProperty[] sSession, int iOpId, int iSoOrgId, ObIdl_MAccTranBilSAgentAccInfoCond sCond, ObIdl_MAccTranBilSAgentAccInfoListHolder listAgentAccInfo, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_ppyAdj(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSAccPpyAdjIn sIn, javax.xml.rpc.holders.LongHolder llRetSoNbr, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int update_unpn(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSUnpnIn sUnpnIn, ObIdl_MAccTranBilSUnpnListHolder listUnpn, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int get_accUnpnRec(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSUnpnRec sUppnRecIn, ObIdl_MAccTranBilSUnpnRecListHolder listUppnRecOut, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int query_adjFileInfo(MObdCommonSOBSessionProperty[] sSession, long llSoNbr, java.lang.String strPhoneId, java.lang.String strBillCycle, java.lang.String strFileName, int iBusiType, java.lang.String dtmBegin, java.lang.String dtmEnd,ObIdl_MAccTranBilSAccAdjFileInfoListHolder listDataOut, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_batchSpDoubleBack(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSAccAdjSpBackInfo[] listIn, ObIdl_MAccTranBilSAccAdjSoInfo sSoInfo, ObIdl_MAccTranBilSAccAdjSpBackInfoListHolder listOut, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_batchSpDoubleBackRefund(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSAccAdjSpBackInfo[] listIn, ObIdl_MAccTranBilSAccAdjSoInfo sSoInfo, ObIdl_MAccTranBilSAccAdjSpBackInfoListHolder listOut, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_batchAdjustBook(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSAccAdjBookInfo[] listIn, ObIdl_MAccTranBilSAccAdjSoInfo sSoInfo, ObIdl_MAccTranBilSAccAdjBookInfoListHolder listOut, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_batchAdjustBookRefund(MObdCommonSOBSessionProperty[] sSession, long llSoNbr, java.lang.String strPhoneId, java.lang.String strBillCycle, java.lang.String strFileName, int iBusiType, java.lang.String dtmBegin, java.lang.String dtmEnd, java.lang.String strOtherSoNbr, int iOpId, int iSoOrgId, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_adjustBook(MObdCommonSOBSessionProperty[] sSession, java.lang.String strPhoneId, long llCustId, java.lang.String strBillCycle, long llAmount, int iFeeItemId, short nAdjustFlag, short nBrand, java.lang.String strOtherSoNbr, java.lang.String strReasonDesc, int iOpId, int iSoOrgId, javax.xml.rpc.holders.LongHolder llRetSoNbr, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_payCreditBook(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSPayCreditBookIn sIn, ObIdl_MAccTranBilSPayCreditBookOutHolder sOut, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_unpayCreditBook(MObdCommonSOBSessionProperty[] sSession, ObIdl_MAccTranBilSUnpayCreditBookIn sIn, ObIdl_MAccTranBilSUnpayCreditBookOutHolder sOut, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_adjustMsBalance(MObdCommonSOBSessionProperty[] sSession, int iFlag, java.lang.String strPhoneId, java.lang.String strOtherSoNbr, long llAdjAmount, int iOpId, int iSoOrgId, java.lang.String strRemark, javax.xml.rpc.holders.LongHolder llRealAdjAmount, javax.xml.rpc.holders.LongHolder llRetSoNbr, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_changeIntellnetCycle(MObdCommonSOBSessionProperty[] sSession, int iFlag, java.lang.String strPhoneId, java.lang.String strOtherSoNbr, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
    public int do_transferSubscriber(MObdCommonSOBSessionProperty[] sSession, int iBusiType, long llOldAcctId, long llNewAcctId, int iOpId, int iSoOrgId, java.lang.String strRemark, java.lang.String strOtherSoNbr, javax.xml.rpc.holders.LongHolder llRetSoNbr, MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, CORBASystemException;
}
