/**
 * ObIdl_MBookSchemeIBkSche.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.asiainfo.obd.bookscheme;

public interface ObIdl_MBookScheme_IBkSche extends java.rmi.Remote {
    public int deal_oneTimePayment(com.asiainfo.obd.bookscheme.MObdCommonSOBSessionProperty[] sSession, java.lang.String strBrand, com.asiainfo.obd.bookscheme.ObIdl_MBookSchemeDefSSegmentFund sSegmentIn, com.asiainfo.obd.bookscheme.ObIdl_MBookSchemeDefSBusinessReceipt sReceiptIn, int iOpId, int iOrgId, com.asiainfo.obd.bookscheme.holders.ObIdl_MAccCommonSAccInvcRecInfoListHolder listReceipt, javax.xml.rpc.holders.LongHolder llPaymentNbr, javax.xml.rpc.holders.LongHolder llRetReceiptNbr, com.asiainfo.obd.bookscheme.holders.MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, com.asiainfo.obd.bookscheme.CORBASystemException;
    public int rollback_backoutPayment(com.asiainfo.obd.bookscheme.MObdCommonSOBSessionProperty[] sSession, java.lang.String strPaymentSoNbr, java.lang.String strReceiptSoNbr, java.lang.String strPayDate, java.lang.String strOtherSoNbr, java.lang.String strReason, int iInvcFlag, int iOpId, int iSoOrgId, com.asiainfo.obd.bookscheme.holders.ObIdl_MAccCommonSAccInvcRecInfoListHolder listInvcRecInfo, javax.xml.rpc.holders.StringHolder strError, com.asiainfo.obd.bookscheme.holders.MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, com.asiainfo.obd.bookscheme.CORBASystemException;
    public int refund_schemeDeposit(com.asiainfo.obd.bookscheme.MObdCommonSOBSessionProperty[] sSession, long llAcctId, java.lang.String strResourceNumber, java.lang.String strPaymentType, long llAmount, java.lang.String strCrmFeeId, java.lang.String strOtherSoNbr, java.lang.String strCrmSapInstanceId, java.lang.String strRemark, com.asiainfo.obd.bookscheme.ObIdl_MBookSchemeDefSSchemeDepositRefund[] listIn, int iOpId, int iOrgId, com.asiainfo.obd.bookscheme.holders.ObIdl_MAccCommonSAccInvcRecInfoListHolder listReceipt, javax.xml.rpc.holders.LongHolder llRetSoNbr, com.asiainfo.obd.bookscheme.holders.MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, com.asiainfo.obd.bookscheme.CORBASystemException;
    public int refund_regularBook(com.asiainfo.obd.bookscheme.MObdCommonSOBSessionProperty[] sSession, long llAcctId, int iBookItemId, long llAmount, java.lang.String strRefundReason, java.lang.String strOtherSoNbr, int iOpId, int iOrgId, java.lang.String strRemark, com.asiainfo.obd.bookscheme.ObIdl_MBookSchemeDefSSchemeDepositRefund[] listIn, com.asiainfo.obd.bookscheme.holders.ObIdl_MAccCommonSAccInvcRecInfoListHolder listReceipt, javax.xml.rpc.holders.LongHolder llRetSoNbr, com.asiainfo.obd.bookscheme.holders.MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, com.asiainfo.obd.bookscheme.CORBASystemException;
    public int refund_msBalance(com.asiainfo.obd.bookscheme.MObdCommonSOBSessionProperty[] sSession, int iOpId, int iSoOrgId, java.lang.String strPhoneId, long llAcctId, long llRefundAmount, long llOriBalance, java.lang.String strTransNbr, int iCancelFlag, java.lang.String strRemark, com.asiainfo.obd.bookscheme.ObIdl_MBookSchemeDefSSchemeDepositRefund[] listIn, com.asiainfo.obd.bookscheme.holders.ObIdl_MAccCommonSAccInvcRecInfoListHolder listReceipt, javax.xml.rpc.holders.LongHolder llBalance, javax.xml.rpc.holders.LongHolder llRetSoNbr, com.asiainfo.obd.bookscheme.holders.MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, com.asiainfo.obd.bookscheme.CORBASystemException;
    public int query_fundBackHistory(com.asiainfo.obd.bookscheme.MObdCommonSOBSessionProperty[] sSession, java.lang.String strPhoneId, java.lang.String strStartTime, java.lang.String strEndTime, java.lang.String strPaymentType, com.asiainfo.obd.bookscheme.holders.ObIdl_MBookSchemeDefSFundbackHistoryQryOutListHolder listFundbackHistoryQryOut, com.asiainfo.obd.bookscheme.holders.MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, com.asiainfo.obd.bookscheme.CORBASystemException;
    public int query_bookSchemeDtl(com.asiainfo.obd.bookscheme.MObdCommonSOBSessionProperty[] sSession, long llAcctId, java.lang.String strStartTime, java.lang.String strEndTime, com.asiainfo.obd.bookscheme.holders.ObIdl_MBookSchemeDefSBookShemeQryOutListHolder listQry, com.asiainfo.obd.bookscheme.holders.MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, com.asiainfo.obd.bookscheme.CORBASystemException;
    public int active_mzoneUser(com.asiainfo.obd.bookscheme.MObdCommonSOBSessionProperty[] sSession, java.lang.String strPhoneId, int iOpId, int iSoOrgId, java.lang.String strOtherSoNbr, javax.xml.rpc.holders.StringHolder strError, com.asiainfo.obd.bookscheme.holders.MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, com.asiainfo.obd.bookscheme.CORBASystemException;
    public int query_oneTimePayment(com.asiainfo.obd.bookscheme.MObdCommonSOBSessionProperty[] sSession, com.asiainfo.obd.bookscheme.ObIdl_MBookSchemeDefSOneTimePaymentQryIn sIn, com.asiainfo.obd.bookscheme.holders.ObIdl_MBookSchemeDefSOneTimePaymentQryOutListHolder listOut, com.asiainfo.obd.bookscheme.holders.MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, com.asiainfo.obd.bookscheme.CORBASystemException;
    public int query_schemePayment(com.asiainfo.obd.bookscheme.MObdCommonSOBSessionProperty[] sSession, com.asiainfo.obd.bookscheme.ObIdl_MBookSchemeDefSSchemePaymentQryIn sIn, com.asiainfo.obd.bookscheme.holders.ObIdl_MBookSchemeDefSSchemePaymentQryOutListHolder listOut, com.asiainfo.obd.bookscheme.holders.MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, com.asiainfo.obd.bookscheme.CORBASystemException;
    public int query_schemeFeeLog(com.asiainfo.obd.bookscheme.MObdCommonSOBSessionProperty[] sSession, com.asiainfo.obd.bookscheme.ObIdl_MBookSchemeDefSShemeFeeLogQryIn sIn, com.asiainfo.obd.bookscheme.holders.ObIdl_MBookSchemeDefSShemeFeeLogQryOutListHolder listOut, com.asiainfo.obd.bookscheme.holders.MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, com.asiainfo.obd.bookscheme.CORBASystemException;
    public int query_bankDepositConfirm(com.asiainfo.obd.bookscheme.MObdCommonSOBSessionProperty[] sSession, java.lang.String strSapId, java.lang.String strEndDate, com.asiainfo.obd.bookscheme.holders.ObIdl_MBookSchemeDefSBankDepositConfirmListHolder listOut, com.asiainfo.obd.bookscheme.holders.MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, com.asiainfo.obd.bookscheme.CORBASystemException;
    public int confirm_bankDepositConfirm(com.asiainfo.obd.bookscheme.MObdCommonSOBSessionProperty[] sSession, int iOpId, int iSoOrgId, com.asiainfo.obd.bookscheme.ObIdl_MBookSchemeDefSBankDepositConfirm sDeposit, int iConfimType, javax.xml.rpc.holders.LongHolder llRetSoNbr, com.asiainfo.obd.bookscheme.holders.MObdCommonSCbsErrorMsgHolder sErrorMsg) throws java.rmi.RemoteException, com.asiainfo.obd.bookscheme.CORBASystemException;
}
