//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.19 at 02:07:53 ���� GMT 
//


package com.asiainfo.boss4.domain.ext;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}brand"/>
 *         &lt;element ref="{}opId"/>
 *         &lt;element ref="{}orgId"/>
 *         &lt;element ref="{}SegmentFund"/>
 *         &lt;element ref="{}BusinessReceipt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "brand",
    "opId",
    "orgId",
    "segmentFund",
    "businessReceipt"
})
@XmlRootElement(name = "OneTimePayment")
public class OneTimePayment {

    @XmlElement(required = true)
    protected String brand;
    @XmlElement(required = true)
    protected String opId;
    @XmlElement(required = true)
    protected String orgId;
    @XmlElement(name = "SegmentFund", required = true)
    protected SegmentFund segmentFund;
    @XmlElement(name = "BusinessReceipt", required = true)
    protected BusinessReceipt businessReceipt;

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the opId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpId() {
        return opId;
    }

    /**
     * Sets the value of the opId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpId(String value) {
        this.opId = value;
    }

    /**
     * Gets the value of the orgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * Sets the value of the orgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgId(String value) {
        this.orgId = value;
    }

    /**
     * Gets the value of the segmentFund property.
     * 
     * @return
     *     possible object is
     *     {@link SegmentFund }
     *     
     */
    public SegmentFund getSegmentFund() {
        return segmentFund;
    }

    /**
     * Sets the value of the segmentFund property.
     * 
     * @param value
     *     allowed object is
     *     {@link SegmentFund }
     *     
     */
    public void setSegmentFund(SegmentFund value) {
        this.segmentFund = value;
    }

    /**
     * Gets the value of the businessReceipt property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessReceipt }
     *     
     */
    public BusinessReceipt getBusinessReceipt() {
        return businessReceipt;
    }

    /**
     * Sets the value of the businessReceipt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessReceipt }
     *     
     */
    public void setBusinessReceipt(BusinessReceipt value) {
        this.businessReceipt = value;
    }

}
