//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.19 at 02:07:53 ���� GMT 
//


package com.asiainfo.boss4.domain.ext;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PaymentList"/>
 *         &lt;element ref="{}RefundList"/>
 *         &lt;element ref="{}UpdateList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paymentList",
    "refundList",
    "updateList"
})
@XmlRootElement(name = "OneTimePaymentItemList")
public class OneTimePaymentItemList {

    @XmlElement(name = "PaymentList", required = true)
    protected PaymentList paymentList;
    @XmlElement(name = "RefundList", required = true)
    protected RefundList refundList;
    @XmlElement(name = "UpdateList", required = true)
    protected UpdateList updateList;

    /**
     * Gets the value of the paymentList property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentList }
     *     
     */
    public PaymentList getPaymentList() {
        return paymentList;
    }

    /**
     * Sets the value of the paymentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentList }
     *     
     */
    public void setPaymentList(PaymentList value) {
        this.paymentList = value;
    }

    /**
     * Gets the value of the refundList property.
     * 
     * @return
     *     possible object is
     *     {@link RefundList }
     *     
     */
    public RefundList getRefundList() {
        return refundList;
    }

    /**
     * Sets the value of the refundList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefundList }
     *     
     */
    public void setRefundList(RefundList value) {
        this.refundList = value;
    }

    /**
     * Gets the value of the updateList property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateList }
     *     
     */
    public UpdateList getUpdateList() {
        return updateList;
    }

    /**
     * Sets the value of the updateList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateList }
     *     
     */
    public void setUpdateList(UpdateList value) {
        this.updateList = value;
    }

}
