//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.19 at 02:07:53 ���� GMT 
//


package com.asiainfo.boss4.domain.ext;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}paymentType"/>
 *         &lt;element ref="{}paymentFlag"/>
 *         &lt;element ref="{}month"/>
 *         &lt;element ref="{}amount"/>
 *         &lt;element ref="{}beginDate"/>
 *         &lt;element ref="{}endDate"/>
 *         &lt;element ref="{}bankCode"/>
 *         &lt;element ref="{}bankCardNbr"/>
 *         &lt;element ref="{}bankCardName"/>
 *         &lt;element ref="{}memo"/>
 *         &lt;element ref="{}crmFeeId"/>
 *         &lt;element ref="{}crmSapInstanceId"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paymentType",
    "paymentFlag",
    "month",
    "amount",
    "beginDate",
    "endDate",
    "bankCode",
    "bankCardNbr",
    "bankCardName",
    "memo",
    "crmFeeId",
    "crmSapInstanceId"
})
@XmlRootElement(name = "Payment")
public class Payment {

    @XmlElement(required = true)
    protected String paymentType;
    protected Short paymentFlag;
    @XmlElement(required = true)
    protected Integer month;
    protected Long amount;
    @XmlElement(required = true)
    protected String beginDate;
    @XmlElement(required = true)
    protected String endDate;
    @XmlElement(required = true)
    protected String bankCode;
    @XmlElement(required = true)
    protected String bankCardNbr;
    @XmlElement(required = true)
    protected String bankCardName;
    @XmlElement(required = true)
    protected String memo;
    protected String crmFeeId;
    @XmlElement(required = true)
    protected String crmSapInstanceId;

    /**
     * Gets the value of the paymentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentType(String value) {
        this.paymentType = value;
    }

    /**
     * Gets the value of the paymentFlag property.
     * 
     */
    public Short getPaymentFlag() {
        return paymentFlag;
    }

    /**
     * Sets the value of the paymentFlag property.
     * 
     */
    public void setPaymentFlag(Short value) {
        this.paymentFlag = value;
    }

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonth(Integer value) {
        this.month = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(Long value) {
        this.amount = value;
    }

    /**
     * Gets the value of the beginDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeginDate() {
        return beginDate;
    }

    /**
     * Sets the value of the beginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeginDate(String value) {
        this.beginDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDate(String value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the bankCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * Sets the value of the bankCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankCode(String value) {
        this.bankCode = value;
    }

    /**
     * Gets the value of the bankCardNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankCardNbr() {
        return bankCardNbr;
    }

    /**
     * Sets the value of the bankCardNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankCardNbr(String value) {
        this.bankCardNbr = value;
    }

    /**
     * Gets the value of the bankCardName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankCardName() {
        return bankCardName;
    }

    /**
     * Sets the value of the bankCardName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankCardName(String value) {
        this.bankCardName = value;
    }

    /**
     * Gets the value of the memo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemo() {
        return memo;
    }

    /**
     * Sets the value of the memo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemo(String value) {
        this.memo = value;
    }

    /**
     * Gets the value of the crmFeeId property.
     * 
     */
    public String getCrmFeeId() {
        return crmFeeId;
    }

    /**
     * Sets the value of the crmFeeId property.
     * 
     */
    public void setCrmFeeId(String value) {
        this.crmFeeId = value;
    }

    /**
     * Gets the value of the crmSapInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrmSapInstanceId() {
        return crmSapInstanceId;
    }

    /**
     * Sets the value of the crmSapInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrmSapInstanceId(String value) {
        this.crmSapInstanceId = value;
    }

}
