//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.19 at 02:07:53 ���� GMT 
//


package com.asiainfo.boss4.domain.ext;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}acctId"/>
 *         &lt;element ref="{}extCustomerId"/>
 *         &lt;element ref="{}paymentTransactionId"/>
 *         &lt;element ref="{}resourceNumber"/>
 *         &lt;element ref="{}OneTimePaymentItemList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acctId",
    "extCustomerId",
    "paymentTransactionId",
    "resourceNumber",
    "oneTimePaymentItemList"
})
@XmlRootElement(name = "SegmentFund")
public class SegmentFund {

    @XmlElement(required = true)
    protected Long acctId;
    @XmlElement(required = true)
    protected String extCustomerId;
    @XmlElement(required = true)
    protected String paymentTransactionId;
    @XmlElement(required = true)
    protected String resourceNumber;
    @XmlElement(name = "OneTimePaymentItemList", required = true)
    protected OneTimePaymentItemList oneTimePaymentItemList;

    /**
     * Gets the value of the acctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Long getAcctId() {
        return acctId;
    }

    /**
     * Sets the value of the acctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctId(Long value) {
        this.acctId = value;
    }

    /**
     * Gets the value of the extCustomerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtCustomerId() {
        return extCustomerId;
    }

    /**
     * Sets the value of the extCustomerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtCustomerId(String value) {
        this.extCustomerId = value;
    }

    /**
     * Gets the value of the paymentTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTransactionId() {
        return paymentTransactionId;
    }

    /**
     * Sets the value of the paymentTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTransactionId(String value) {
        this.paymentTransactionId = value;
    }

    /**
     * Gets the value of the resourceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceNumber() {
        return resourceNumber;
    }

    /**
     * Sets the value of the resourceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceNumber(String value) {
        this.resourceNumber = value;
    }

    /**
     * Gets the value of the oneTimePaymentItemList property.
     * 
     * @return
     *     possible object is
     *     {@link OneTimePaymentItemList }
     *     
     */
    public OneTimePaymentItemList getOneTimePaymentItemList() {
        return oneTimePaymentItemList;
    }

    /**
     * Sets the value of the oneTimePaymentItemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OneTimePaymentItemList }
     *     
     */
    public void setOneTimePaymentItemList(OneTimePaymentItemList value) {
        this.oneTimePaymentItemList = value;
    }

}
